package zt.qf.com.greendaodemo2.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zt.qf.com.greendaodemo2.db.Node;

import zt.qf.com.greendaodemo2.db.NodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nodeDaoConfig;

    private final NodeDao nodeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nodeDaoConfig = daoConfigMap.get(NodeDao.class).clone();
        nodeDaoConfig.initIdentityScope(type);

        nodeDao = new NodeDao(nodeDaoConfig, this);

        registerDao(Node.class, nodeDao);
    }
    
    public void clear() {
        nodeDaoConfig.clearIdentityScope();
    }

    public NodeDao getNodeDao() {
        return nodeDao;
    }

}
