package zt.qf.com.greendaodemo2.db;

import org.greenrobot.greendao.annotation.*;

import java.util.Date;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "NODE".
 */
@Entity
public class Node {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private java.util.Date birthday;

    @Generated
    public Node() {
    }

    public Node(String name)
    {
        this.name = name;
        this.birthday = new Date();
    }

    public Node(Long id) {
        this.id = id;
    }

    @Generated
    public Node(Long id, String name, java.util.Date birthday) {
        this.id = id;
        this.name = name;
        this.birthday = birthday;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        return "Node{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", birthday=" + birthday +
                '}';
    }
}
